---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Homelab Services"
subtitle: "Crstian's"
logo: "assets//tools/gopher-astronaut.webp"
# icon: "fas fa-skull-crossbones" Optional icon

# Optional message
#
message:
  # url: https://....
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Hi !"
  content: "These are my home server services, running under NixOS. Find more about me on crstian.me"

# Optional navbar
links:
  - name: "Personal Page"
    icon: "fas fa-user"
    url: "https://crstian.me"
    target: '_blank'
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/Crstian19"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Gitlab"
    icon: "fab fa-gitlab"
    target: '_blank'
    url: "https://gitlab.com/Crstian"
  - name: "Shell"
    icon: "fas fa-terminal"
    target: '_blank'
    url: "https://shell.crstian.me"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "File Sharing"
    icon: "fas fa-share-alt"
    items:
      - name: "Rutorrent"
        logo: "assets/tools/rutorrent.png"
        subtitle: "P2P Bittorrent client"
        tag: "P2P"
        tagstyle: "is-success"
        url: "https://rutorrent.crstian.me/"
        target: '_blank' # optional html a tag target attribute
      - name: "Torrent Downloads"
        logo: "assets/tools/caddy.svg"
        subtitle: "Open source web server"
        tag: "WebServer"
        target: '_blank'
        tagstyle: "is-success"
        url: "https://downloads.crstian.me"
 #     - name: "Pyload"
 #       logo: "assets/tools/pyload.png"
 #       subtitle: "Open Source download manager"
 #       tag: "Python"
 #       tagstyle: "is-success"
 #       url: "https://pyload.crstian.me"
 #       target: '_blank'
      - name: "Private Downloads"
        logo: "assets/tools/caddy.svg"
        subtitle: "Open source web server"
        tag: "WebServer"
        target: '_blank'
        tagstyle: "is-success"
        url: "https://private.crstian.me"
      - name: "Public Downloads"
        logo: "assets/tools/caddy.svg"
        subtitle: "Open source web server"
        tag: "WebServer"
        target: '_blank'
        tagstyle: "is-success"
        url: "https://public.crstian.me"
      - name: "Updog"
        logo: "assets/tools/updog.png"
        subtitle: "Python's SimpleHTTPServer"
        tag: "WebServer"
        target: '_blank'
        tagstyle: "is-success"
        url: "https://updog.crstian.me"

  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        subtitle: "HTTP reverse proxy and load balancer"
        tag: "Proxy"
        url: "https://traefik.crstian.me"
      - name: "Watchtower"
        logo: "assets/tools/watchtower.png"
        subtitle: "Automatically update Docker containers"
        tag: "Update"
        tagstyle: "is-success"

      - name: "Netdata Server"
        logo: "assets/tools/logonetdata.png"
        subtitle: "Real-time and health monitoring"
        url: "https://netdata.crstian.me"
        tag: "Stats"
        tagstyle: "is-success"
      - name: "Netdata Router Linksys"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/router.png"
        subtitle: "Real-time and health monitoring"
        url: "https://linksys.crstian.me"
        tag: "Stats"
        tagstyle: "is-success"
      - name: "Grafana"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/grafana.png"
        subtitle: "Analytics visualization web application"
        url: "https://grafana.crstian.me/"
        tag: "Dashboard"
        tagstyle: "is-success"
      - name: "Prometheus"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/prometheus.png"
        subtitle: "Event monitoring and alerting"
        url: "http://server.lan:9090"
        tag: "Dashboard"
        tagstyle: "is-success"
      - name: "Gotify"
        logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/gotify.png"
        subtitle: "Server for sending messages"
        url: "https://gotify.crstian.me/"
        tag: "Notifications"
        tagstyle: "is-success"
      - name: "Loki"
        logo: "https://raw.githubusercontent.com/Crstian19/homer-icons/master/png/loki.png"
        subtitle: "Log system"
        url: "http://server.lan:3100/"
        tag: "Logs"
        tagstyle: "is-success"
    #  - name: "Grafana"
    #    logo: "assets/tools/grafana.png"
    #    subtitle: "Metric analytics & dashboards"
    #    url: "https://grafana.com/"
    #  - name: "Kibana"
    #    logo: "assets/tools/elastic.png"
    #    subtitle: "Explore & visualize logs"
    #    tag: "elk"
    #    url: "https://www.elastic.co/products/kibana"
    #  - name: "Website monitoring"
    #    logo: "assets/tools/pingdom.png"
    #    subtitle: "Pingdom public reports overview"
    #    tag: "CI"
    #    url: "https://www.pingdom.com/"
  - name: "Information"
    icon: "fas fa-rocket"
    items:
      - name: "FreshRSS"
        logo: "assets/tools/freshrss.png"
        subtitle: "Self-hosted RSS feed aggregator"
        tag: "RSS"
        tagstyle: "is-success"
        url: "https://rss.crstian.me"
      - name: "TS3"
        logo: "assets/tools/ts3.png"
        subtitle: "ts.crstian.me"
        tag: "TS3"
        tagstyle: "is-success"
        url: "ts3server://ts.crstian.me"
      - name: "Clarkson"
        logo: "assets/tools/clarkson.png"
        subtitle: "Web-based fuel logging dashboard"
        url: "https://gasofa.crstian.me"
        tag: "Fuel Dashboard"
        tagstyle: "is-success"
      - name: "Home Assistant"
        logo: "assets/tools/HassioLogo.webp"
        subtitle: "Open source home automation"
        url: "https://home.crstian.me"
        tag: "Home"
        tagstyle: "is-success"
      - name: "Lychee"
        logo: "assets/tools/google-photos.svg"
        subtitle: "Self-hosted photo-management"
        url: "https://photos.crstian.me"
        tag: "Photos"
        tagstyle: "is-success"

 # - name: "In progress"
 #   icon: "fas fa-spinner"
 #   items:
 #     - name: "Octoprint"
 #       logo: "assets/tools/octoprintLogo.png"
 #       subtitle: "Web interface for my 3D printer"
 #       tag: "3D Printer"
 #        url: "https://octoprint.crstian.me"

  - name: "Developing"
    icon: "far fa-file-code"
    items:
      - name: "Gitea"
        logo: "assets/tools/gitea.png"
        subtitle: "Git solution for my code"
        tag: "Git"
        tagstyle: "is-success"
        url: "https://git.crstian.me"
        target: '_blank'
      - name: "PhantomBot"
        logo: "assets/tools/phantombot.png"
        subtitle: "Open source interactive Twitch bot"
        tag: "Twitch"
        tagstyle: "is-success"
        url: "https://twitch.crstian.me"
        target: '_blank'
  - name: Games
    icon: "fab fa-twitch"
    items:
      - name: "Minecraft Server"
        logo: "assets/tools/minecraft.png"
        subtitle: "My own Minecraft Server"
        tag: "Minecraft"
        target: '_blank'
        tagstyle: "is-success"
  - name: Hosting
    icon: ""
    items:
      - name: "Minecraft Server"
        logo: "assets/tools/minecraft.png"
        subtitle: "My own Minecraft Server"
        tag: "Minecraft"
        target: '_blank'
        tagstyle: "is-success"

   